// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMVAe3qH-sy-LhSGF6QnFdKdQ1UUnrrOs',
    appId: '1:273673934089:web:ac50415401211e1142afd8',
    messagingSenderId: '273673934089',
    projectId: 'speedo-life',
    authDomain: 'speedo-life.firebaseapp.com',
    storageBucket: 'speedo-life.firebasestorage.app',
    measurementId: 'G-RQBWTMLS5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9vCd_OIDnGjJ_89zK2pDz-afRDgc2nGg',
    appId: '1:273673934089:android:d7ed7b0997fd13a242afd8',
    messagingSenderId: '273673934089',
    projectId: 'speedo-life',
    storageBucket: 'speedo-life.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIFtOVGykxo5SE0lwj_BBNBvap_cuzIFk',
    appId: '1:273673934089:ios:b32774e12170336442afd8',
    messagingSenderId: '273673934089',
    projectId: 'speedo-life',
    storageBucket: 'speedo-life.firebasestorage.app',
    iosBundleId: 'com.example.speedoLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIFtOVGykxo5SE0lwj_BBNBvap_cuzIFk',
    appId: '1:273673934089:ios:b32774e12170336442afd8',
    messagingSenderId: '273673934089',
    projectId: 'speedo-life',
    storageBucket: 'speedo-life.firebasestorage.app',
    iosBundleId: 'com.example.speedoLife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMVAe3qH-sy-LhSGF6QnFdKdQ1UUnrrOs',
    appId: '1:273673934089:web:5a0a6d93f057db4442afd8',
    messagingSenderId: '273673934089',
    projectId: 'speedo-life',
    authDomain: 'speedo-life.firebaseapp.com',
    storageBucket: 'speedo-life.firebasestorage.app',
    measurementId: 'G-1PY3TG79Q6',
  );
}
